---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  namespace: default
  labels:
    app: python-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
      - name: python-server
        image: skaalex/python_server:0.0.3
        ports:
        - containerPort: 5555
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: python-server
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 5555
  selector:
    app: python-server
