name: Build_and_deploy_to_stage
on:
  workflow_dispatch:
    inputs:
      image_version:
        description: Version of Docker Image
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Python Lint
      uses: cclauss/Find-Python-syntax-errors-action@master

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Docker Build
      run: docker build  -t ${{ secrets.DOCKER_LOGIN }}/python_server:${{ github.event.inputs.image_version }} .

    - name: Docker Push
      run: |
        docker tag  ${{ secrets.DOCKER_LOGIN }}/python_server:${{ github.event.inputs.image_version }} ${{ secrets.DOCKER_LOGIN }}/python_server:latest
        docker push ${{ secrets.DOCKER_LOGIN }}/python_server:${{ github.event.inputs.image_version }}
        docker push ${{ secrets.DOCKER_LOGIN }}/python_server:latest
    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    # - name: Deploy to stage
    #   run: |
    #     mkdir -p ~/.kube/
    #     echo ${{ kube_config_stage }} | base64 --decode >~/.kube/config
    #     kubectl apply -f .k8s/stage.yaml
